generic-service:
  nameOverride: hmpps-contacts-ui
  productId: "DPS096" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources
  serviceAccountName: "hmpps-contacts-ui"

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-contacts-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-contacts-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "hmpps-contacts-ui" # Your audit service name
    CONTACTS_API_REFERENCE_DATA_CACHE_TTL: 300

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-contacts-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SIGN_IN_CLIENT_ID: "SIGN_IN_CLIENT_ID"
      SIGN_IN_CLIENT_SECRET: "SIGN_IN_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
      AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"
    contacts-ui-sentry:
      SENTRY_DSN: "SENTRY_DSN"
      SENTRY_LOADER_SCRIPT_ID: "SENTRY_LOADER_SCRIPT_ID"

  allowlist:
    groups:
      - internal
      - prisons

generic-prometheus-alerts:
  targetApplication: hmpps-contacts-ui
