enum AuthorisedRoles {
  ROLE_PRISON = 'ROLE_PRISON',
  ROLE_CONTACTS_ADMINISTRATOR = 'ROLE_CONTACTS_ADMINISTRATOR',
  ROLE_CONTACTS_AUTHORISER = 'ROLE_CONTACTS_AUTHORISER',
}

export default AuthorisedRoles
