enum AuthorisedRoles {
  ROLE_PRISON = 'ROLE_PRISON',
  ROLE_CONTACTS_ADMINISTRATOR = 'ROLE_CONTACTS_ADMINISTRATOR',
  ROLE_CONTACTS_AUTHORISER = 'ROLE_CONTACTS_AUTHORISER',
  ROLE_GLOBAL_SEARCH = 'ROLE_GLOBAL_SEARCH',
}

export default AuthorisedRoles
