enum ReferenceCodeType {
  'TITLE' = 'TITLE',
  'RELATIONSHIP' = 'RELATIONSHIP',
  'PHONE_TYPE' = 'PHONE_TYPE',
  'DOMESTIC_STS' = 'DOMESTIC_STS',
  'ID_TYPE' = 'ID_TYPE',
  'GENDER' = 'GENDER',
  'LANGUAGE' = 'LANGUAGE',
  'RESTRICTION' = 'RESTRICTION',
  'ADDRESS_TYPE' = 'ADDRESS_TYPE',
}
export default ReferenceCodeType
