enum ReferenceCodeType {
  'TITLE' = 'TITLE',
  'RELATIONSHIP_TYPE' = 'RELATIONSHIP_TYPE',
  'SOCIAL_RELATIONSHIP' = 'SOCIAL_RELATIONSHIP',
  'OFFICIAL_RELATIONSHIP' = 'OFFICIAL_RELATIONSHIP',
  'PHONE_TYPE' = 'PHONE_TYPE',
  'DOMESTIC_STS' = 'DOMESTIC_STS',
  'ID_TYPE' = 'ID_TYPE',
  'GENDER' = 'GENDER',
  'LANGUAGE' = 'LANGUAGE',
  'RESTRICTION' = 'RESTRICTION',
  'ADDRESS_TYPE' = 'ADDRESS_TYPE',
  'CITY' = 'CITY',
  'COUNTY' = 'COUNTY',
  'COUNTRY' = 'COUNTRY',
}
export default ReferenceCodeType
