import { Alert } from '../../data/alertsApiTypes'

export default class TestAlertsData {
  static getAlert = ({
    alertUuid = '8cdadcf3-b003-4116-9956-c99bd8df6a00',
    prisonNumber = 'A1234AA',
    alertCode = {
      alertTypeCode: 'A',
      alertTypeDescription: 'Alert type description',
      code: 'ABC',
      description: 'Alert code description',
    },
    description = 'Alert description',
    authorisedBy = 'A. Nurse, An Agency',
    activeFrom = '2021-09-27',
    activeTo = '2022-07-15',
    isActive = true,
    createdAt = '2021-09-27T14:19:25',
    createdBy = 'USER1234',
    createdByDisplayName = 'Firstname Lastname',
    lastModifiedAt = '2022-07-15T15:24:56',
    lastModifiedBy = 'USER1234',
    lastModifiedByDisplayName = 'Firstname Lastname',
    activeToLastSetAt = '2022-07-15T15:24:56',
    activeToLastSetBy = 'USER1234',
    activeToLastSetByDisplayName = 'Firstname Lastname',
    madeInactiveAt = '2022-07-15T15:24:56',
    madeInactiveBy = 'USER1234',
    madeInactiveByDisplayName = 'Firstname Lastname',
    prisonCodeWhenCreated = 'LEI',
  }: Partial<Alert> = {}): Alert =>
    ({
      alertUuid,
      prisonNumber,
      alertCode,
      description,
      authorisedBy,
      activeFrom,
      activeTo,
      isActive,
      createdAt,
      createdBy,
      createdByDisplayName,
      lastModifiedAt,
      lastModifiedBy,
      lastModifiedByDisplayName,
      activeToLastSetAt,
      activeToLastSetBy,
      activeToLastSetByDisplayName,
      madeInactiveAt,
      madeInactiveBy,
      madeInactiveByDisplayName,
      prisonCodeWhenCreated,
    }) as Alert
}
