/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/contact': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create a new contact
     * @description Creates a new contact that is not yet associated with any prisoner.
     */
    post: operations['createContact']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisoner/{prisonNumber}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to get a specific prisoner by prison number */
    get: operations['getPrisoner']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisoner/{prisonNumber}/contact': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to fetch all contacts for a specific prisoner by prisoner number and active status */
    get: operations['getAllContacts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/contact/{contactId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get contact
     * @description Gets a contact by their id
     */
    get: operations['getContact']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Request to create a new contact */
    CreateContactRequest: {
      /**
       * @description The title of the contact, if any
       * @example Mr
       */
      title?: string | null
      /**
       * @description The last name of the contact
       * @example Doe
       */
      lastName: string
      /**
       * @description The first name of the contact
       * @example John
       */
      firstName: string
      /**
       * @description The middle name of the contact, if any
       * @example William
       */
      middleName?: string | null
      /**
       * Format: date
       * @description The date of birth of the contact, if known
       * @example 1980-01-01
       */
      dateOfBirth?: string | null
      /**
       * @description The id of the user creating the contact
       * @example JD000001
       */
      createdBy: string
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      errorCode?: string
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description The details of a contact as an individual */
    Contact: {
      /**
       * Format: int64
       * @description The id of the contact
       * @example 123456
       */
      id: number
      /**
       * @description The title of the contact, if any
       * @example Mr
       */
      title?: string | null
      /**
       * @description The last name of the contact
       * @example Doe
       */
      lastName: string
      /**
       * @description The first name of the contact
       * @example John
       */
      firstName: string
      /**
       * @description The middle name of the contact, if any
       * @example William
       */
      middleName?: string | null
      /**
       * Format: date
       * @description The date of birth of the contact, if known
       * @example 1980-01-01
       */
      dateOfBirth?: string | null
      /**
       * @description The id of the user who created the contact
       * @example JD000001
       */
      createdBy: string
      /**
       * Format: date-time
       * @description The timestamp of when the contact was created
       * @example 2024-01-01T00:00:00Z
       */
      createdTime: string
    }
    /** @description Describes the details of a prisoner's contact */
    PrisonerContactSummary: {
      /**
       * Format: int64
       * @description The unique identifier for the prisoner contact
       * @example 123456
       */
      prisonerContactId: number
      /**
       * Format: int64
       * @description The unique identifier for the contact
       * @example 654321
       */
      contactId: number
      /**
       * @description Prisoner number (NOMS ID)
       * @example A1234BC
       */
      prisonerNumber: string
      /**
       * @description The surname of the contact
       * @example Doe
       */
      surname: string
      /**
       * @description The forename of the contact
       * @example John
       */
      forename: string
      /**
       * @description The middle name of the contact, if any
       * @example William
       */
      middleName?: string | null
      /**
       * Format: date
       * @description The date of birth of the contact
       * @example 1980-01-01
       */
      dateOfBirth: string
      /**
       * @description The relationship code between the prisoner and the contact
       * @example FRI
       */
      relationshipCode: string
      /**
       * @description The description of the relationship
       * @example Friend
       */
      relationshipDescription: string
      /**
       * @description Flat number in the address, if any
       * @example Flat 1
       */
      flat?: string | null
      /**
       * @description Property name or number
       * @example 123
       */
      property: string
      /**
       * @description Street name
       * @example Baker Street
       */
      street: string
      /**
       * @description Area or locality, if any
       * @example Marylebone
       */
      area?: string | null
      /**
       * @description City code
       * @example LON
       */
      cityCode: string
      /**
       * @description County code
       * @example GLA
       */
      countyCode: string
      /**
       * @description Postal code
       * @example NW1 6XE
       */
      postCode: string
      /**
       * @description Country code
       * @example GBR
       */
      countryCode: string
      /**
       * @description Indicates whether the contact is an approved visitor
       * @example true
       */
      approvedVisitor: boolean
      /**
       * @description Is this contact the prisoner's next of kin?
       * @example false
       */
      nextOfKin: boolean
      /**
       * @description Is this contact the prisoner's emergency contact?
       * @example true
       */
      emergencyContact: boolean
      /**
       * @description Is this contact aware of the prisoner's charges?
       * @example true
       */
      awareOfCharges: boolean
      /**
       * @description Any additional comments
       * @example Close family friend
       */
      comments?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  createContact: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateContactRequest']
      }
    }
    responses: {
      /** @description Created the contact successfully */
      201: {
        headers: {
          /**
           * @description The URL where you can load the contact
           * @example /contact/123456
           */
          Location?: unknown
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Contact']
        }
      }
      /** @description The request has invalid or missing fields */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The prison number of the prisoner who's contacts will be returned
         * @example A1234BC
         */
        prisonNumber: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of all contacts for the prisoner */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PrisonerContactSummary']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getAllContacts: {
    parameters: {
      query?: {
        /** @description Whether to include only active (true) or inactive (false) contacts */
        active?: boolean
      }
      header?: never
      path: {
        /**
         * @description The prison number of the prisoner who's contacts will be returned
         * @example A1234BC
         */
        prisonNumber: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of all contacts for the prisoner */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PrisonerContactSummary']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The Prisoner was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getContact: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The id of the contact
         * @example 123456
         */
        contactId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Found the contact */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Contact']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description No contact with that id could be found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
}
