---
# Per environment values which override defaults in hmpps-contacts-ui/values.yaml

generic-service:
  ingress:
    host: contacts.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: 'https://contacts.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api.prison.service.justice.gov.uk'
    COMPONENT_API_URL: 'https://frontend-components.hmpps.service.justice.gov.uk' # used by hmpps-connect-dps-components module
    DPS_HOME_PAGE_URL: 'https://digital.prison.service.justice.gov.uk'
    PRISONER_SEARCH_API_URL: 'https://prisoner-search.prison.service.justice.gov.uk'
    PRISON_API_URL: 'https://prison-api.prison.service.justice.gov.uk'
    CONTACTS_API_URL: 'https://personal-relationships-api.hmpps.service.justice.gov.uk'
    ORGANISATIONS_API_URL: 'https://organisations-api.hmpps.service.justice.gov.uk'
    ALERTS_API_URL: 'https://alerts-api.hmpps.service.justice.gov.uk'
    COMMON_COMPONENTS_ENABLED: true
    SENTRY_ENVIRONMENT: PRODUCTION
    FEATURE_ENABLED_PRISONS: 'KMI,GNI,SPI,LGI,DWI,HOI,WWI,LEI,LWI,BWI,BLI,SLI,IWI'
    AUDIT_ENABLED: 'false'

generic-prometheus-alerts:
  alertSeverity: hmpps-contacts-ui-prod
