---
# Per environment values which override defaults in hmpps-contacts-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: contacts-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: 'https://contacts-preprod.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-preprod.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-preprod.prison.service.justice.gov.uk'
    COMPONENT_API_URL: 'https://frontend-components-preprod.hmpps.service.justice.gov.uk' # used by hmpps-connect-dps-components module
    DPS_HOME_PAGE_URL: 'https://digital-preprod.prison.service.justice.gov.uk'
    PRISONER_SEARCH_API_URL: 'https://prisoner-search-preprod.prison.service.justice.gov.uk'
    PRISON_API_URL: 'https://prison-api-preprod.prison.service.justice.gov.uk'
    CONTACTS_API_URL: 'https://contacts-api-preprod.hmpps.service.justice.gov.uk'
    COMMON_COMPONENTS_ENABLED: true
    ENVIRONMENT_NAME: PRE-PRODUCTION
    SENTRY_ENVIRONMENT: PRE-PRODUCTION
    AUDIT_ENABLED: 'false'

generic-prometheus-alerts:
  alertSeverity: managing-contacts-alerts-non-prod
